server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/trip
  jpa:
    show-sql: true
  artemis:
    broker-url: tcp://localhost:61616
    pool:
      use-anonymous-producers: true
    mode: native

  jms:
    pub-sub-domain: true
    template:
      delivery-mode: persistent
      qos-enabled: true
    listener:
      acknowledge-mode: auto

jms:
  topic:
    trip-request: trip
    trip-proposal: proposal

api:
  external:
    base-url: http://assd-traffic-service-progetto2.router.default.svc.cluster.local/assdTrafficService/rest/

